  spring:
    http:
      encoding:
        force: true
        ### 模版引擎编码为UTF-8
        charset: UTF-8
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/local?characterEncoding=UTF-8

  mybatis:
    mapper-locations:  classpath:mapper/*.xml
    type-aliases-package: com.lgy.pojo
  lgy:
    name: 李高原
    age: 222
  thymeleaf:
    prefix: classpath:/templates/ #prefix：指定模板所在的目录
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    suffix:  .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5